<a href="https://colab.research.google.com/github/kiruthisrahul2002-collab/attention-based-multivariate-time-series-forecasting/blob/main/Copy_of_LoanApproval.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("loan_approval_1000.csv")

In [ ]:
df.head()

   Age    Income  Loan_Amount  Credit_Score Employment_Type  Loan_Approved
0   59   77761.0       417505           337        Salaried              0
1   49  141178.0       328226           487        Salaried              0
2   35   56368.0       312805           356   Self-Employed              0
3   28   26783.0       218484           319        Salaried              0
4   41  131530.0       315064           572   Self-Employed              0

In [ ]:
df.isna().sum()

Age                 0
Income             50
Loan_Amount         0
Credit_Score        0
Employment_Type    50
Loan_Approved       0
dtype: int64

In [ ]:
len(df)

1000

In [ ]:
df['Employment_Type'].value_counts()

Employment_Type
Salaried         471
Self-Employed    287
Unemployed       192
Name: count, dtype: int64

In [ ]:
me=df['Income'].mean()
mo=df['Employment_Type'].mode()[0]

In [ ]:
df['Income']=df['Income'].fillna(me)
df['Employment_Type']=df['Employment_Type'].fillna(mo)

In [ ]:
df.isna().sum()

Age                0
Income             0
Loan_Amount        0
Credit_Score       0
Employment_Type    0
Loan_Approved      0
dtype: int64

In [ ]:
from sklearn.preprocessing import LabelEncoder
lr=LabelEncoder()
df['Employment_Type']=lr.fit_transform(df['Employment_Type'])

In [ ]:
df

     Age    Income  Loan_Amount  Credit_Score  Employment_Type  Loan_Approved
0     59   77761.0       417505           337                0              0
1     49  141178.0       328226           487                0              0
2     35   56368.0       312805           356                1              0
3     28   26783.0       218484           319                0              0
4     41  131530.0       315064           572                1              0
..   ...       ...          ...           ...              ...            ...
995   58  112447.0       259717           572                2              0
996   22  134994.0       314167           544                2              0
997   27  109899.0       169654           749                0              1
998   38   40049.0       240868           546                2              0
999   47   95717.0       130073           819                0              1

[1000 rows x 6 columns]

In [ ]:
lr.classes_

array(['Salaried', 'Self-Employed', 'Unemployed'], dtype=object)

In [ ]:
x=df.drop('Loan_Approved',axis=1)
y=df['Loan_Approved']
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [ ]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression(max_iter=1000)
lr.fit(x_train,y_train)

LogisticRegression(max_iter=1000)

In [ ]:
y_predict=lr.predict(x_test)

In [ ]:
y_predict

array([0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 1])

In [ ]:
y_test

697    0
343    0
797    1
592    1
358    0
      ..
662    0
157    0
702    0
421    0
548    1
Name: Loan_Approved, Length: 200, dtype: int64

In [ ]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_predict))

              precision    recall  f1-score   support

           0       0.85      0.88      0.87       142
           1       0.68      0.62      0.65        58

    accuracy                           0.81       200
   macro avg       0.76      0.75      0.76       200
weighted avg       0.80      0.81      0.80       200